// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsFxmQeTnvtmRl8uYP4LVupt5gC2MxWYQ',
    appId: '1:1091501890060:web:bb76d0102f7f31532aec29',
    messagingSenderId: '1091501890060',
    projectId: 'shoaibproj-cb1ef',
    authDomain: 'shoaibproj-cb1ef.firebaseapp.com',
    storageBucket: 'shoaibproj-cb1ef.firebasestorage.app',
    measurementId: 'G-LE0WP2KWBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXtuFJWEjWcKVj3NjqKSF_huHKswthGzw',
    appId: '1:1091501890060:android:b5674115a6b72c0b2aec29',
    messagingSenderId: '1091501890060',
    projectId: 'shoaibproj-cb1ef',
    storageBucket: 'shoaibproj-cb1ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMHjhfNnR3KtnvYrICoOopOQZE-iO330Y',
    appId: '1:1091501890060:ios:608c85199eb593432aec29',
    messagingSenderId: '1091501890060',
    projectId: 'shoaibproj-cb1ef',
    storageBucket: 'shoaibproj-cb1ef.firebasestorage.app',
    iosBundleId: 'se.fff.ghj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMHjhfNnR3KtnvYrICoOopOQZE-iO330Y',
    appId: '1:1091501890060:ios:608c85199eb593432aec29',
    messagingSenderId: '1091501890060',
    projectId: 'shoaibproj-cb1ef',
    storageBucket: 'shoaibproj-cb1ef.firebasestorage.app',
    iosBundleId: 'se.fff.ghj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsFxmQeTnvtmRl8uYP4LVupt5gC2MxWYQ',
    appId: '1:1091501890060:web:d51be1faeadc9dec2aec29',
    messagingSenderId: '1091501890060',
    projectId: 'shoaibproj-cb1ef',
    authDomain: 'shoaibproj-cb1ef.firebaseapp.com',
    storageBucket: 'shoaibproj-cb1ef.firebasestorage.app',
    measurementId: 'G-Z088VSCKND',
  );
}
